name: Azure DevOps Task Update

on:
  push:
    branches:
      - main

jobs:
  update-task:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install azure-devops msrest

    - name: Run Python script
      run: python updateTask.py
      env:
        BUILD_SOURCEVERSIONMESSAGE: ${{ github.event.head_commit.message }}
        AZURE_DEVOPS_URL: ${{ secrets.ORGANIZATION_URL }}
        AZURE_DEVOPS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
